const AppActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    REGISTER: 'REGISTER',
    ERROR: 'ERROR',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    SEARCH: 'SEARCH'
};

export { AppActionsConstants}
