const AppActionsConstants = {
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    REGISTER: 'REGISTER',
    ERROR: 'ERROR',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    SEARCH: 'SEARCH',
    SEARCH_USER: 'SEARCH_USER',
    SEARCH_USER_CLEAR: 'SEARCH_USER_CLEAR',
    WRITE_REVIEW: 'WRITE_REVIEW',
    EDIT_REVIEW: 'EDIT_REVIEW',
    DELETE_REVIEW: 'DELETE_REVIEW',
    SEARCH_SUGGESTS: 'SEARCH_SUGGESTS',
    LOGOUT: 'LOGOUT',
};

export { AppActionsConstants}
