const ReviewActionsConstants = {
    GET_REVIEWS: 'GET_REVIEWS',
    GET_REVIEWS_BY_REST: 'GET_REVIEWS_BY_REST',
    GET_REVIEWS_BY_USER: 'GET_REVIEWS_BY_USER',
    ADD_REVIEW: 'ADD_REVIEW',
    DELETE_REVIEW: 'DELETE_REVIEW',
    REVIEWS_LOADING: 'REVIEWS_LOADING',
    EDIT_REVIEW: 'EDIT_REVIEW',
    //ADD SORT OPTIONS
    EDIT_SORT_TYPE : 'EDIT_SORT_TYPE',
    EDIT_SORT_SINCE : 'EDIT_SORT_SINCE'
};

export {ReviewActionsConstants}


